### ISSUE TITLE
Add WebKit-compatible backdrop-filter blur

### ISSUE THREAD

**Issue by seidior** [Paryssatis/crochet-stitch-tracker#19]
### Describe the Feature / Enhancement

Currently, WebKit (as used in Safari for both iOS and Mac) does not recognize the plain, unprefixed

```css
backdrop-filter: blur(7px);
```

CSS declaration. In addition to this declaration, you should also add the prefixed attribute

```css
-webkit-backdrop-filter: blur(7px);
```

If you apply both of these to an element, such as with this selector:

```css
.child {
  backdrop-filter: blur(7px);
  -webkit-backdrop-filter: blur(7px);
}
```

Then you should have a backdrop blur in Chrome, Firefox, and Safari.

### Correct Project Selected

- [X] This issue is linked to the appropriate project

### Labels

- [X] This issue has appropriate labels.
